### PR TITLE
Add Supernova report parser script

### PR DESCRIPTION
**Pull request by jgruselius**
Something I wrote to get all those Supernova numbers into spreadsheets. Damn inconvenient format they use.. :sweat: Maybe this is something you can have use for @remiolsen?

### CODE REVIEW

**Comment by ewels** [comment]
Would it be useful to have a Supernova MultiQC module?

**Comment by remiolsen** [comment]
Cool! But Supernova already includes a `.csv` file in its output containing the same numbers as the report. I just spread the `.txt` report around because it at least include some form of description (although sparse) of what these values mean.

@ewels That would be really useful. I'm thinking of automating what I do manually now. Basically running Supernova then Quast and BUSCO.

**Comment by ewels** [comment]
I think Quast and BUSCO are already supported. If Supernova creates a .csv file then a MultiQC module should be pretty trivial.

**Comment by jgruselius** [comment]
@remiolsen it does? Haha well I only had access to the text files. But nevermind it was not so much work anyway!

**Pull request closed without merging**
