### PR TITLE
Added new patterns for zendesk attachment backups

### PR DESCRIPTION
**Pull request by ewels**
Partial rewrite of the zendesk backup script.

* Now takes multiple inputs and iterates through them
* Can handle `.zip` files as well as `tickets.xml` files directly
* Better logging so that you know what's happening

This script should be run manually by Mattias when he does the manual zendesk backups. Will be stored on tools in `/var/local/zendesk`

Also reformatted the readme a bit.

### CODE REVIEW

**Comment by ewels** [comment]
Hmm, I think your comments are all referring to the code shown in commit e81ad96b726e7e541dc6705e556464b56aabfe06 - none of this code is written by me though. I had a merge conflict so had to bring updates from the SciLifeLab fork into my fork. So that commit is just all of the changes that have happened since I last forked from the head repository.

The only things changing in this PR are in `README.md` and `zendesk_backup_attachments.py`, plus some `chmod` of other files. You can see these changes in the "Files Changed" tab in this PR. That tab ignores all of the stuff you mention as the pull request won't change that. This PR is adding 88 lines and removing 36 lines:
image

So, I'm pleased to report that in `zendesk_backup_attachments.py` I am already using `from __future__ import print_function` `print()` (not `absolute_import` as I'm not importing anything).

**Comment by pekrau** [comment]
OK, then. Do you merge, or I?

**Comment by ewels** [comment]
If you're happy with it, you can merge it..

**Comment by ewels** [comment]
👍

**Pull request merged**
